export const ReduxAction = {
    SIGN_IN : "SIGN_IN",
    SIGN_OUT : "SIGN_OUT",
    CREATE_STREAM : "CREATE_STREAME",
    FETCH_STREAMS : "FETCH_STREAMS",
    FETCH_STREAM : "FETCH_STREAM",
    DELETE_STREAM : "DELETE_STREAM",
    EDIT_STREAM : "EDIT_STREAM"
}